repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
    exclude: '\.*conda/.*'
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: '\.txt$|\.tsv$'
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: detect-private-key
  - id: check-added-large-files
    args: ['--maxkb=1000']

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.26.0
  hooks:
  - id: markdownlint
    args: ['--config', '.markdownlint.json']
