name: CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@v2

      - name: Install pylint
        run: pip install pylint pylint-quotes

      - name: Run pylint
        run: pylint **/*.py
