name: CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
        
    - name: Install packages
      run: conda install -c conda-forge pre-commit pylint

    - name: pre-commit
      run: pre-commit run --all-files
