name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install packages
        run: |
          pip install pre-commit

      - name: pre-commit
        run: |
          pre-commit run --all-files
